name: MineJS
description: MineJS for Bukkit
main: org.netherald.minejs.bukkit.MineJsBukkit
api-version: 1.17
version: 0.1
author: Netherald
authors:
  - Myoung2
  - R2turnTrue
  - Project_TL
commands:
  minejs:
    description: MineJS command
    aliases:
      - js
    usage: /<command> reload
softdepend:
  - ProtocolLib
libraries:
  - net.projecttl:InventoryGUI-api:4.2.0